enableChart: true

global:
  ngcImagePullSecretName: "inference-container-pull-secret"

# Image pull secrets for Docker Hub and other registries
imagePullSecrets:
  - name: "inference-container-pull-secret"
  - name: "docker-hub-secret"
  - name: "ngc-docker-reg-secret"

resources:
  dispatch:
    requests:
      cpu: "2"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 2Gi
  database:
    requests:
      cpu: "2"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 2Gi
  mosquitto:
    requests:
      cpu: "1"
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 1Gi


dispatch:
  ingress:
    enabled: false
    missionUrl: ""
  replicaCount: 1
  image:
    repository: nvcr.io/nvidia/isaac/mission-dispatch
    tag: 4.3.0

database:
  replicaCount: 1
  image:
    repository: nvcr.io/nvidia/isaac/mission-database
    tag: 4.3.0

postgres:
  enabled: true
  fullnameOverride: postgres
  auth:
    database: mission
    username: postgres-user
    existingSecret: mission-dispatch-postgres # align prefix with fullnameOverride
    secretKeys:
      userPasswordKey: postgres-password
  service:
    ports:
      postgresql: 5432
  primary:
    persistence: # az33 does not allow creating pvc, networking policy or pdb
      enabled: false
    networkPolicy:
      enabled: false
    pdb:
      create: false
  # Update repos to use bitnamilegacy
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  metrics:
    image:
      repository: bitnamilegacy/postgres-exporter

mosquitto:
  enabled: true
  image:
    repository: docker.io/eclipse-mosquitto
    tag: 2.0.22
    pullPolicy: Always

mqtt:
  host: ""
  transport: "tcp"
  username: ""
  password: ""

